[ENG-94] Register self as peer on startup
skip-mev/mev-tendermint pull request #43
Opened 2022-10-08 22:26 UTC by wllmshao

Added some optional config fields under sidecar that if populated, will cause the node to register itself with the sentinel on startup.

These new fields are:
- API key (corresponding to the validator for this node)
- Validator addr (onchain address of the validator that has this node as a sentry)
- Relayer RPC address (ip:port of the sentinel)

On startup, if all these are present and an explicit `p2p.external_addr` is set in the config, then the node will send a post request to register itself with the sentinel on startup.
If any of these are not set, then the node will not attempt to register itself.

Some open questions:
- Should we move the new fields out from sidecar into a different section?
- Should we reuse `p2p.external_addr` or create a new config field for it? Is there any situation where we want the external addr used for p2p to be different from the one auto-registered with the sentinel?

2022-10-12 21:10 UTC, MaghnusM requested changes
Looks good - main point here is renaming suggestions and also adding peers as unconditional and, most importantly, persistent

2022-10-12 21:10 UTC, MaghnusM commented on config/toml.go
> +relayer = "{{ .Sidecar.Relayer }}"
I could rename `relayer` to `relayer_conn_string`

2022-10-12 21:10 UTC, MaghnusM commented on config/toml.go
> +validator_addr = "{{ .Sidecar.ValidatorAddr }}"
I would rename `validator_addr` to `validator_addr_hash`

2022-10-12 21:10 UTC, MaghnusM commented on config/toml.go
> +validator_addr = "{{ .Sidecar.ValidatorAddr }}"
Otherwise confusing with their `junovalcon1...` address

2022-10-12 21:10 UTC, MaghnusM commented on cmd/tendermint/commands/root.go
> +				if conf.P2P.PrivatePeerIDs[len(conf.P2P.PrivatePeerIDs)-1:] == "," {
Where is the logic to add to `unconditional_peers` and `persistent_peers`? Already implemented?

2022-10-12 23:35 UTC, wllmshao commented on config/toml.go
> +validator_addr = "{{ .Sidecar.ValidatorAddr }}"
Good point, done

2022-10-12 23:35 UTC, wllmshao commented on config/toml.go
> +relayer = "{{ .Sidecar.Relayer }}"
Agreed, done

2022-10-12 23:36 UTC, wllmshao commented on cmd/tendermint/commands/root.go
> +				if conf.P2P.PrivatePeerIDs[len(conf.P2P.PrivatePeerIDs)-1:] == "," {
Added now. Previously we would rely on the sentinel doing this, now it is persistent and unconditional both ways.
Also made it private so that the sentinel address doesn't get gossipped via pex.

2022-10-12 23:42 UTC, wllmshao commented on cmd/tendermint/commands/root.go
> +				if conf.P2P.PrivatePeerIDs[len(conf.P2P.PrivatePeerIDs)-1:] == "," {
These changes are in node/node.go btw

2022-10-13 00:18 UTC, MaghnusM commented on cmd/tendermint/commands/root.go
> +				if conf.P2P.PrivatePeerIDs[len(conf.P2P.PrivatePeerIDs)-1:] == "," {
Awesome

2022-10-13 00:26 UTC, MaghnusM requested changes
Looks good - main point here is renaming suggestions and also adding peers as unconditional and, most importantly, persistent

2022-10-13 00:26 UTC, MaghnusM commented on node/node.go
> +	if n.config.Sidecar.APIKey != "" && n.config.Sidecar.ValidatorAddrHash != "" && n.config.Sidecar.RelayerConnString != "" {
Can you add some erroring prints / feedback depending on which parts of config are missing

2022-10-13 00:26 UTC, MaghnusM commented on rpc/core/status.go
> +	if relayer := env.SidecarConfig.RelayerConnString; relayer != "" {
Same here, would add a status thing which is like "you're not connected since you didn't set a relayer id"

2022-10-13 00:59 UTC, wllmshao commented on node/node.go
> +	if n.config.Sidecar.APIKey != "" && n.config.Sidecar.ValidatorAddrHash != "" && n.config.Sidecar.RelayerConnString != "" {
added

2022-10-13 01:00 UTC, wllmshao commented on rpc/core/status.go
> +	if relayer := env.SidecarConfig.RelayerConnString; relayer != "" {
Kind of want to hold off on this -- this would make the field have 3 potential values (not set, not connected, connected).
I think it's easier to easier to monitor if it's just a bool, and can't imagine vals getting more value out of seeing if the relayer id is set here, since they should know from the config.

2022-10-13 14:12 UTC, bpiv400 commented on config/toml.go
> +validator_addr = "{{ .Sidecar.ValidatorAddr }}"
I would call this "validator_addr_hex" since that's how Todd identified it

2022-10-13 14:13 UTC, bpiv400 commented on rpc/core/status.go
> +	if relayer := env.SidecarConfig.RelayerConnString; relayer != "" {
Agreed with Will on this

2022-10-13 18:03 UTC, wllmshao commented on config/toml.go
> +validator_addr = "{{ .Sidecar.ValidatorAddr }}"
Done

2022-10-13 21:09 UTC, merged