[ENG-132] Unit tests for new mev-tendermint functionality
skip-mev/mev-tendermint pull request #57
Opened 2022-10-22 22:59 UTC by wllmshao

`mempool/v0/clist_mempool.go`:
- Added test that sidecar gets reaped first
- Added test that txes in sidecar don't get reaped again in mempool reap

`mempool/v0/clist_sidecar.go`:
- Moved sidecar-specific tests to their own file
- Added test for `GetEnforcedBundleSize`
- Added test for `GetCurrBundleSize`

`p2p/sentinel.go`:
- Slight refactor for testability: building json data for post data moved to separate function. goroutine for making post request moved to separate function
- Added test that json body gets formed properly and goroutine makes post request with correct data to the expected endpoint

`p2p/switch.go`:
- Added test for AddRelayerPeer

2022-10-23 19:28 UTC, MaghnusM requested changes
Nice, good cleanup. Asked some questions, worried about the segfault we had with Body.Close() in test that @bpiv400 fixed last time.

Did you test this on the testnet with the most up-to-date sentinel and nodes that run (and don't run) this latest version of mev-tendermint?

We can cut this into a `.7` with validator preferences if that sounds good.

2022-10-23 19:28 UTC, MaghnusM commented on p2p/switch_test.go
> +func TestAddRelayerPeer(t *testing.T) {
want to add a test that expects an error if you try to use the wrong one?

2022-10-23 19:28 UTC, MaghnusM commented on p2p/sentinel_test.go
> +package p2p
where is the test here? Just a lack of errors? Does `postRequestRoutine` return any errors to catch?

2022-10-23 19:28 UTC, MaghnusM commented on p2p/sentinel.go
> +		defer resp.Body.Close()
@bpiv400 do the various Body.Close() still pose a segfault like they did in prod in these cases? Should there be extra checks?

2022-10-23 20:02 UTC, bpiv400 requested changes
I left one comment on the body closing logic, and I left one comment that we should add a test to make sure we're not panicing if the server returns a 500 or failure for any reason.

2022-10-23 20:02 UTC, bpiv400 commented on p2p/sentinel.go
> +		defer resp.Body.Close()
No this isn't a seg fault issue now. 

I wonder if there's a case where: 
* resp is not nil 
* there is an error 
such that we should close Body but do not. 

Perhaps the best way to do this be to move resp.Body.Close() out of the else and have a new conditional afterward: 

```
if resp != nil {
    defer resp.Body.Close()
}
```

2022-10-23 20:02 UTC, bpiv400 commented on p2p/sentinel_test.go
> +func TestPostRequestRoutine(t *testing.T) {
This is a neat way to test it

2022-10-23 20:02 UTC, bpiv400 commented on p2p/sentinel_test.go
> +}
We should add an additional test to make sure we're catching errors / not seg faulting when the server returns a 500 or any other kind of failure

2022-10-24 22:56 UTC, wllmshao commented on p2p/switch_test.go
> +func TestAddRelayerPeer(t *testing.T) {
This doesn't hardcode what relayer string to expect, but I did add a test to assert there is an an err if an invalid relayer string is passed.

2022-10-24 22:57 UTC, wllmshao commented on p2p/sentinel_test.go
> +package p2p
This makes a mock http server, which receives the post request and then checks the request details (path, headers, body) to make sure they match expected values.

2022-10-24 22:58 UTC, wllmshao commented on p2p/sentinel.go
> +		defer resp.Body.Close()
Added an additional `resp != nil && resp.Body != nil` check before Close() call

2022-10-24 23:00 UTC, wllmshao commented
This refactors the sentinel registration code but isn't tested on testnet yet.
Can we do the registration loop logic after merging this and then test that together? @MaghnusM

2022-10-24 23:04 UTC, wllmshao commented on p2p/sentinel_test.go
> +}
Added

2022-10-25 01:16 UTC, merged