Api reconnection
skip-mev/mev-tendermint pull request #60
Opened 2022-10-24 17:16 UTC by MaghnusM

This PR adds peer registration via the sentinel `RegisterPeer` API on a consistent loop upon loss of reconnection, alongside peer gossip reconnection.

Tested on testnet.

2022-10-24 19:37 UTC, wllmshao commented on README.md
> +![Group 6.png](mev-tendermint%20(%207)%201d6a6a8f65cb41af9825bc5865a60923/Group_6.png)
This image needs to be added to the commit I think? Doesn't seem to be showing up in the readme on github on this branch.

2022-10-24 19:37 UTC, wllmshao commented on p2p/switch.go
> +			RegisterWithSentinel(sw.Logger, sw.RelayerAPIKey, sw.ValidatorAddrHex, string(sw.nodeInfo.ID()), relayerIP+rpcPort)
Probably not a mainnet blocker but this creates unnecessary traffic on the registration api. I think it'd be better to add looping logic to `RegisterWithSentinel` itself, and stop when the response indicates success. That way we don't actually change the switch at all.

2022-10-24 20:06 UTC, MaghnusM commented on README.md
> +![Group 6.png](mev-tendermint%20(%207)%201d6a6a8f65cb41af9825bc5865a60923/Group_6.png)
FIxed

2022-10-24 20:13 UTC, MaghnusM commented on p2p/switch.go
> +			RegisterWithSentinel(sw.Logger, sw.RelayerAPIKey, sw.ValidatorAddrHex, string(sw.nodeInfo.ID()), relayerIP+rpcPort)
Hmm... okay. I was initially thinking it's good for them to try to re-register on a process that spawns from the lost peer since it's possible we blew away the entry in the db somehow, or the sentinel call somehow went through successfully but didn't register properly or save to db (i.e. we had an issue on our end). Remember, these calls will only happen until the node is reconnected

2022-10-24 22:04 UTC, bpiv400 commented on p2p/switch.go
> +			RegisterWithSentinel(sw.Logger, sw.RelayerAPIKey, sw.ValidatorAddrHex, string(sw.nodeInfo.ID()), relayerIP+rpcPort)
Agreed with @wllmshao on this. 

We should just maintain the invariant that a successful response from the sentinel API === properly registered. 

If any of the steps there fail internally, we return an error message.

2022-10-24 22:12 UTC, bpiv400 requested changes

2022-10-24 22:12 UTC, bpiv400 commented on p2p/switch.go
> +			RegisterWithSentinel(sw.Logger, sw.RelayerAPIKey, sw.ValidatorAddrHex, string(sw.nodeInfo.ID()), relayerIP+rpcPort)
Another reason this logic should be moved to node: 

This might actually fail to solve the problem we're trying to fix. 

* The initial RegisterWithSentinel call could fail
* Dial Peer could succeed (thus not calling RegisterWithSentinel again) and leaving the registration in an inconsistent state where we are peered with the sentinel, but the sentinel does not know to send this validator bundles. 

My recommendation is the same as Will's: Let's move this logic to RegisterWithSentinel, have it loop and retry the endpoint every 30 seconds until it gets a successful response message.

2022-10-24 22:41 UTC, MaghnusM commented on p2p/switch.go
> +			RegisterWithSentinel(sw.Logger, sw.RelayerAPIKey, sw.ValidatorAddrHex, string(sw.nodeInfo.ID()), relayerIP+rpcPort)
I would have gotten away with it if it weren't for those Medellin kids!

2022-10-25 01:15 UTC, MaghnusM commented on p2p/switch.go
> +			RegisterWithSentinel(sw.Logger, sw.RelayerAPIKey, sw.ValidatorAddrHex, string(sw.nodeInfo.ID()), relayerIP+rpcPort)
Fixed

2022-10-25 22:07 UTC, merged