[ENG-211] Add sidecar support for v1 mempool
skip-mev/mev-tendermint pull request #70
Opened 2022-11-10 21:52 UTC by wllmshao

- Create new `ReapedTxs` type which is just a `types.Txs` and a `[]int64 GasWanteds`. This is used as the new return type of the mempool and sidecar reap functions.
- Create a new `mempool/mev_reap.go` file with a function that merges sidecar and mempool `ReapedTxs` up to `maxBytes, maxGas`
- Remove sidecar dependence from v0 mempool
- Add sidecar channel to v1 mempool reactor
- Create and use sidecar in `node.go` regardless of which mempool version is used

2022-11-12 02:12 UTC, MaghnusM requested changes
such a good upgrade, well – just some small comments but this is so much cleaner than before

Will look more closely tomorrow

2022-11-12 02:12 UTC, MaghnusM commented on mempool/mev_reap.go
> +		fmt.Println("[mev-tendermint]: reaped sidecar mev transaction", sidecarTx.Hash())
I'd consider shortening, can be heavy real estate on the logs

2022-11-12 02:12 UTC, MaghnusM commented on mempool/mev_reap.go
> +		totalGas = newTotalGas
May want to consolidate logic here, first case you check with added amount for bytes, then update running total var. Second case you add, then check total, then set running amount to total.

2022-11-12 02:12 UTC, MaghnusM commented on mempool/v0/clist_mempool.go
> +				Txs:        txs[:len(txs)-1],
isn't this just all of them? just set as txs?

2022-11-12 02:12 UTC, MaghnusM commented on mempool/v0/clist_mempool.go
> +				GasWanteds: gasWanteds[:len(txs)-1],
same here?

2022-11-12 02:12 UTC, MaghnusM commented on mempool/v1/reactor.go
> +					panic(err)
this will only panic the peer thread and stop it right?

2022-11-14 15:47 UTC, wllmshao commented on mempool/mev_reap.go
> +		fmt.Println("[mev-tendermint]: reaped sidecar mev transaction", sidecarTx.Hash())
agreed, switching to `GetLastNumBytesFromTx(sidecarTx, 20)`

2022-11-14 15:50 UTC, wllmshao commented on mempool/mev_reap.go
> +		totalGas = newTotalGas
I agree but this is the way original tendermint does it so didn't want to change what isn't broken. Going to leave as is.

2022-11-14 15:50 UTC, wllmshao commented on mempool/v0/clist_mempool.go
> +				Txs:        txs[:len(txs)-1],
It's exclusive of last index so this will exclude the last element

2022-11-14 16:09 UTC, wllmshao commented on mempool/v1/reactor.go
> +					panic(err)
Good question, this will actually panic and there's no recovery on this call stack, so this would take the node down.
I'm removing the panic on both v0 and v1 `broadcastTxSidecarRoutine`s, instead just logging and skipping the send. Don't want a failed sidecar marshal to take down a node.

2022-11-14 16:16 UTC, wllmshao commented on mempool/mev_reap.go
> +		fmt.Println("[mev-tendermint]: reaped sidecar mev transaction", sidecarTx.Hash())
Switched to use `getLastNumBytesFromTx`, same for mempltx logging below

2022-11-15 14:12 UTC, bpiv400 requested changes
Overall, very good IMO.

Just some structural things: 
1. Why did we change the mempoolTx data structure names and location from mempool.go to v0 mempool? It seems like this belongs in the types along with ReapedTxs package even though we only use it in v0 now, it looks like. 
2. If sidecar is used for both v0 and v1, it probably shouldn't go into the v0 package. It seems like it belongs in its own package? Seems strange that v1 now imports the v0 package in a couple locations. 

And a note about testing: It seems like the combined reap logic is undertested right now, since we don't have tests around the edge and failure cases related to max bytes and max gas being exceeded in the sidecar or in the mempool after the sidecar.

2022-11-15 14:12 UTC, bpiv400 commented on mempool/mev_reap_test.go
> +func TestCombineSidecarAndMempoolTxs_SkipsSidecarTxsInMempoolReap(t *testing.T) {
I think we should also add tests to ensure that if the side car exceeds max gas and/or max bytes, things work as expected. 

Same for the case where the mempool plus the sidecar exceeds those values but mempool alone does not

2022-11-15 14:12 UTC, bpiv400 commented on mempool/v0/clist_mempool.go
> +type mempoolTx struct {
Why did we move this out of mempool.go and into here + why did we lowercase the fields?

2022-11-15 14:12 UTC, bpiv400 commented on mempool/v1/reactor.go
>  func (memR *Reactor) Receive(chID byte, src p2p.Peer, msgBytes []byte) {
Not looking at this super closely -- assuming we're pretty much copy pasting the logic here

2022-11-15 19:36 UTC, wllmshao commented on mempool/mev_reap_test.go
> +func TestCombineSidecarAndMempoolTxs_SkipsSidecarTxsInMempoolReap(t *testing.T) {
Good point, added these tests.

2022-11-15 19:36 UTC, wllmshao commented on mempool/v0/clist_mempool.go
> +type mempoolTx struct {
I fully reset this to original tendermint, where `mempoolTx` is private and only part of v0.
We made a public `MempoolTx` for our sidecar implementation for mev-tendermint, which is no longer necessary.

2022-11-15 19:36 UTC, wllmshao commented on mempool/v1/reactor.go
>  func (memR *Reactor) Receive(chID byte, src p2p.Peer, msgBytes []byte) {
Yeah, we're copying. But an additional change piggybacked on this is that if the `MEVMessage` marshal fails in `broadcastSidecarTxRoutine`, we no longer panic, just log and continue. This is changed in both v0 and v1 reactors.

2022-11-15 19:36 UTC, wllmshao commented
> Why did we change the mempoolTx data structure names and location from mempool.go to v0 mempool? It seems like this belongs in the types along with ReapedTxs package even though we only use it in v0 now, it looks like.

See comment reply above.

> If sidecar is used for both v0 and v1, it probably shouldn't go into the v0 package. It seems like it belongs in its own package? Seems strange that v1 now imports the v0 package in a couple locations.

Agreed with this, moved the sidecar into mempool, out of v0. Also removed its dependence on the v0 `mempoolTx`

> And a note about testing: It seems like the combined reap logic is undertested right now, since we don't have tests around the edge and failure cases related to max bytes and max gas being exceeded in the sidecar or in the mempool after the sidecar.

Agreed, added more tests for mev_reap. Also added the sidecar tests from v0 reactor to v1 reactor.

2022-11-16 00:29 UTC, bpiv400 approved these changes

2022-11-16 01:07 UTC, merged