[ENG-314] Safeguard reap from empty blocks
skip-mev/mev-tendermint pull request #85
Opened 2022-12-14 21:12 UTC by wllmshao

Diff is self explanatory

2022-12-16 03:13 UTC, bpiv400 requested changes

2022-12-16 03:13 UTC, bpiv400 commented on state/execution.go
> +	if len(txs) == 0 {
nit: Feels like this actually belongs in the CombineSidecarAndMempoolTxs function, since it's tightly coupled. (We would never call it without this sanity check afterward)

2022-12-16 20:05 UTC, wllmshao commented on state/execution.go
> +	if len(txs) == 0 {
That's a good point, I agree. Makes much more sense this way. Updated PR.

2022-12-19 23:34 UTC, bpiv400 approved these changes

2022-12-20 01:04 UTC, merged